# Generated by Django 4.2.5 on 2023-11-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_emailverifyrecord_alter_userprofile_nike_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nike_name',
            field=models.CharField(blank=True, default='', max_length=23, verbose_name='个人博客昵称'),
        ),
    ]
