# Generated by Django 4.2.5 on 2023-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['sort'], 'verbose_name': '侧边栏', 'verbose_name_plural': '侧边栏'},
        ),
        migrations.AddField(
            model_name='sidebar',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, default='', help_text='如果设置的不是HTML类型,可为空', max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='sort',
            field=models.PositiveIntegerField(default=1, help_text='序号越小越靠前', verbose_name='排序'),
        ),
    ]
