# Generated by Django 4.2.5 on 2023-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_sidebar_options_sidebar_is_hot_sidebar_pv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='pv',
        ),
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
