# Generated by Django 4.2.5 on 2023-10-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_sidebar_is_hot_remove_sidebar_pv_post_is_hot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['sort'], 'verbose_name': '侧边栏项目管理', 'verbose_name_plural': '侧边栏项目管理'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
