# Generated by Django 4.2.5 on 2023-10-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_categories_alter_category_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
