# Generated by Django 4.2.5 on 2023-10-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_category_posts_remove_post_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(related_name='post_categories', to='blog.post'),
        ),
    ]
