# Generated by Django 4.2.5 on 2023-10-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_category_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
    ]
