# Generated by Django 4.2.5 on 2023-10-31 11:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_category_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tie_zi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
