# Generated by Django 4.2.5 on 2023-10-31 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_tie_zi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tie_zi',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
    ]
