# Generated by Django 4.2.5 on 2023-11-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_hot',
        ),
    ]
