# Generated by Django 4.2.5 on 2023-11-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_favorites_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='is_favorite',
        ),
    ]
