# Generated by Django 4.2.5 on 2023-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_favorites_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
    ]
