# Generated by Django 4.2.5 on 2023-11-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_favorites_is_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='is_favorites',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
    ]
