# Generated by Django 4.2.5 on 2023-11-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_favorites_is_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='is_favorites',
            new_name='is_favorite',
        ),
    ]
