# Generated by Django 4.2.5 on 2023-11-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_rename_is_favorites_favorites_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否为热门文章'),
        ),
    ]
