# Generated by Django 4.2.5 on 2023-11-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_post_is_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_hot',
        ),
    ]
