# Generated by Django 4.2.5 on 2023-11-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_post_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '搜索'), (2, '更新文章'), (3, '热门文章'), (4, '评论'), (5, '文章归档'), (6, 'HTML')], default=1, verbose_name='展示类型'),
        ),
    ]
